version: '3.8'
services:

  # AuthService with its own PostgreSQL DB
  userservice:
    build: ./userservice
    ports:
      - "3000:3000"
    env_file:
      - ./userservice/.env
    depends_on:
      - userdb
      - user-migrate

  user-migrate:
    env_file:
      - ./userservice/.env
    image: migrate/migrate
    command: [
      "sh", "-c", "sleep 30 && migrate -path /migrations -database postgres://user_service:password@userdb:5432/userservicedb?sslmode=disable up"
    ]
    volumes:
      - ./userservice/migrations:/migrations
    depends_on:
      - userdb

  userdb:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userservicedb

  # BookCategoryService with its own PostgreSQL DB
  bookcategoryservice:
    build: ./bookcategoryservice
    ports:
      - "3020:3020"
    env_file:
      - ./bookcategoryservice/.env
    depends_on:
      - bookcategorydb
      - category-migrate
      - userservice

  category-migrate:
    image: migrate/migrate
    command:  [
      "sh", "-c", "sleep 30 && migrate -path /migrations -database postgres://bookcategory_user:password@bookcategorydb:5432/bookcategoryservicedb?sslmode=disable up"
    ]
    volumes:
      - ./bookcategoryservice/migrations:/migrations
    depends_on:
      - bookcategorydb

  bookcategorydb:
    image: postgres:alpine
    environment:
      POSTGRES_USER: bookcategory_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookcategoryservicedb



 # BookService with its own PostgreSQL DB
  bookservice:
    build: ./bookservice
    ports:
      - "3010:3010"
    env_file:
      - ./bookservice/.env
    depends_on:
      - bookdb
      - book-migrate
      - userservice
      - bookcategoryservice

  book-migrate:
    image: migrate/migrate
    env_file:
      - ./bookservice/.env
    command: [
      "sh", "-c", "sleep 30 && migrate -path /migrations -database postgres://book_user:password@bookdb:5432/bookservicedb?sslmode=disable up"
    ]
    volumes:
      - ./bookservice/migrations:/migrations
    depends_on:
      - bookdb

  bookdb:
    image: postgres:alpine
    environment:
      POSTGRES_USER: book_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookservicedb
